/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.sqlite.tables;


import dev.entree.vchest.sqlite.DefaultSchema;
import dev.entree.vchest.sqlite.Keys;
import dev.entree.vchest.sqlite.tables.records.ChestRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chest extends TableImpl<ChestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>chest</code>
     */
    public static final Chest CHEST = new Chest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChestRecord> getRecordType() {
        return ChestRecord.class;
    }

    /**
     * The column <code>chest.chest_num</code>.
     */
    public final TableField<ChestRecord, Integer> CHEST_NUM = createField(DSL.name("chest_num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>chest.chest_player_id</code>.
     */
    public final TableField<ChestRecord, Integer> CHEST_PLAYER_ID = createField(DSL.name("chest_player_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private Chest(Name alias, Table<ChestRecord> aliased) {
        this(alias, aliased, null);
    }

    private Chest(Name alias, Table<ChestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>chest</code> table reference
     */
    public Chest(String alias) {
        this(DSL.name(alias), CHEST);
    }

    /**
     * Create an aliased <code>chest</code> table reference
     */
    public Chest(Name alias) {
        this(alias, CHEST);
    }

    /**
     * Create a <code>chest</code> table reference
     */
    public Chest() {
        this(DSL.name("chest"), null);
    }

    public <O extends Record> Chest(Table<O> child, ForeignKey<O, ChestRecord> key) {
        super(child, key, CHEST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ChestRecord> getPrimaryKey() {
        return Keys.CHEST__;
    }

    @Override
    public Chest as(String alias) {
        return new Chest(DSL.name(alias), this);
    }

    @Override
    public Chest as(Name alias) {
        return new Chest(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Chest rename(String name) {
        return new Chest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Chest rename(Name name) {
        return new Chest(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
