/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.mysql;


import dev.entree.vchest.mysql.tables.Slot;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in mc_virtual_chest.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SLOT_SLOT_PLAYER_ID = Internal.createIndex(DSL.name("slot_player_id"), Slot.SLOT, new OrderField[] { Slot.SLOT.SLOT_PLAYER_ID, Slot.SLOT.SLOT_CHEST_NUM }, false);
}
