/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.mysql;


import dev.entree.vchest.mysql.tables.Chest;
import dev.entree.vchest.mysql.tables.Player;
import dev.entree.vchest.mysql.tables.Slot;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McVirtualChest extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mc_virtual_chest</code>
     */
    public static final McVirtualChest MC_VIRTUAL_CHEST = new McVirtualChest();

    /**
     * The table <code>mc_virtual_chest.chest</code>.
     */
    public final Chest CHEST = Chest.CHEST;

    /**
     * The table <code>mc_virtual_chest.player</code>.
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>mc_virtual_chest.slot</code>.
     */
    public final Slot SLOT = Slot.SLOT;

    /**
     * No further instances allowed
     */
    private McVirtualChest() {
        super("mc_virtual_chest", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chest.CHEST,
            Player.PLAYER,
            Slot.SLOT
        );
    }
}
