/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.mysql;


import dev.entree.vchest.mysql.tables.Chest;
import dev.entree.vchest.mysql.tables.Player;
import dev.entree.vchest.mysql.tables.Slot;


/**
 * Convenience access to all tables in mc_virtual_chest.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mc_virtual_chest.chest</code>.
     */
    public static final Chest CHEST = Chest.CHEST;

    /**
     * The table <code>mc_virtual_chest.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>mc_virtual_chest.slot</code>.
     */
    public static final Slot SLOT = Slot.SLOT;
}
