/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.mysql.tables;


import dev.entree.vchest.mysql.Keys;
import dev.entree.vchest.mysql.McVirtualChest;
import dev.entree.vchest.mysql.tables.Player.PlayerPath;
import dev.entree.vchest.mysql.tables.Slot.SlotPath;
import dev.entree.vchest.mysql.tables.records.ChestRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Chest extends TableImpl<ChestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mc_virtual_chest.chest</code>
     */
    public static final Chest CHEST = new Chest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChestRecord> getRecordType() {
        return ChestRecord.class;
    }

    /**
     * The column <code>mc_virtual_chest.chest.chest_num</code>.
     */
    public final TableField<ChestRecord, Integer> CHEST_NUM = createField(DSL.name("chest_num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mc_virtual_chest.chest.chest_player_id</code>.
     */
    public final TableField<ChestRecord, Integer> CHEST_PLAYER_ID = createField(DSL.name("chest_player_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mc_virtual_chest.chest.chest_expires_at</code>.
     */
    public final TableField<ChestRecord, LocalDateTime> CHEST_EXPIRES_AT = createField(DSL.name("chest_expires_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("NULL", SQLDataType.LOCALDATETIME)), this, "");

    private Chest(Name alias, Table<ChestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Chest(Name alias, Table<ChestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mc_virtual_chest.chest</code> table reference
     */
    public Chest(String alias) {
        this(DSL.name(alias), CHEST);
    }

    /**
     * Create an aliased <code>mc_virtual_chest.chest</code> table reference
     */
    public Chest(Name alias) {
        this(alias, CHEST);
    }

    /**
     * Create a <code>mc_virtual_chest.chest</code> table reference
     */
    public Chest() {
        this(DSL.name("chest"), null);
    }

    public <O extends Record> Chest(Table<O> path, ForeignKey<O, ChestRecord> childPath, InverseForeignKey<O, ChestRecord> parentPath) {
        super(path, childPath, parentPath, CHEST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChestPath extends Chest implements Path<ChestRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChestPath(Table<O> path, ForeignKey<O, ChestRecord> childPath, InverseForeignKey<O, ChestRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChestPath(Name alias, Table<ChestRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChestPath as(String alias) {
            return new ChestPath(DSL.name(alias), this);
        }

        @Override
        public ChestPath as(Name alias) {
            return new ChestPath(alias, this);
        }

        @Override
        public ChestPath as(Table<?> alias) {
            return new ChestPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : McVirtualChest.MC_VIRTUAL_CHEST;
    }

    @Override
    public UniqueKey<ChestRecord> getPrimaryKey() {
        return Keys.KEY_CHEST_PRIMARY;
    }

    @Override
    public List<ForeignKey<ChestRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHEST_IBFK_1);
    }

    private transient PlayerPath _player;

    /**
     * Get the implicit join path to the <code>mc_virtual_chest.player</code>
     * table.
     */
    public PlayerPath player() {
        if (_player == null)
            _player = new PlayerPath(this, Keys.CHEST_IBFK_1, null);

        return _player;
    }

    private transient SlotPath _slot;

    /**
     * Get the implicit to-many join path to the
     * <code>mc_virtual_chest.slot</code> table
     */
    public SlotPath slot() {
        if (_slot == null)
            _slot = new SlotPath(this, null, Keys.SLOT_IBFK_1.getInverseKey());

        return _slot;
    }

    @Override
    public Chest as(String alias) {
        return new Chest(DSL.name(alias), this);
    }

    @Override
    public Chest as(Name alias) {
        return new Chest(alias, this);
    }

    @Override
    public Chest as(Table<?> alias) {
        return new Chest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Chest rename(String name) {
        return new Chest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Chest rename(Name name) {
        return new Chest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Chest rename(Table<?> name) {
        return new Chest(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chest where(Condition condition) {
        return new Chest(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chest where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chest where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chest where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chest where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chest where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chest where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chest where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chest whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chest whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
