/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.mysql.tables;


import dev.entree.vchest.mysql.Indexes;
import dev.entree.vchest.mysql.Keys;
import dev.entree.vchest.mysql.McVirtualChest;
import dev.entree.vchest.mysql.tables.Chest.ChestPath;
import dev.entree.vchest.mysql.tables.records.SlotRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Slot extends TableImpl<SlotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mc_virtual_chest.slot</code>
     */
    public static final Slot SLOT = new Slot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SlotRecord> getRecordType() {
        return SlotRecord.class;
    }

    /**
     * The column <code>mc_virtual_chest.slot.slot_slot</code>.
     */
    public final TableField<SlotRecord, Integer> SLOT_SLOT = createField(DSL.name("slot_slot"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mc_virtual_chest.slot.slot_chest_num</code>.
     */
    public final TableField<SlotRecord, Integer> SLOT_CHEST_NUM = createField(DSL.name("slot_chest_num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mc_virtual_chest.slot.slot_player_id</code>.
     */
    public final TableField<SlotRecord, Integer> SLOT_PLAYER_ID = createField(DSL.name("slot_player_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mc_virtual_chest.slot.slot_item_bytes</code>.
     */
    public final TableField<SlotRecord, byte[]> SLOT_ITEM_BYTES = createField(DSL.name("slot_item_bytes"), SQLDataType.BLOB(16777215).nullable(false), this, "");

    private Slot(Name alias, Table<SlotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Slot(Name alias, Table<SlotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>mc_virtual_chest.slot</code> table reference
     */
    public Slot(String alias) {
        this(DSL.name(alias), SLOT);
    }

    /**
     * Create an aliased <code>mc_virtual_chest.slot</code> table reference
     */
    public Slot(Name alias) {
        this(alias, SLOT);
    }

    /**
     * Create a <code>mc_virtual_chest.slot</code> table reference
     */
    public Slot() {
        this(DSL.name("slot"), null);
    }

    public <O extends Record> Slot(Table<O> path, ForeignKey<O, SlotRecord> childPath, InverseForeignKey<O, SlotRecord> parentPath) {
        super(path, childPath, parentPath, SLOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SlotPath extends Slot implements Path<SlotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SlotPath(Table<O> path, ForeignKey<O, SlotRecord> childPath, InverseForeignKey<O, SlotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SlotPath(Name alias, Table<SlotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SlotPath as(String alias) {
            return new SlotPath(DSL.name(alias), this);
        }

        @Override
        public SlotPath as(Name alias) {
            return new SlotPath(alias, this);
        }

        @Override
        public SlotPath as(Table<?> alias) {
            return new SlotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : McVirtualChest.MC_VIRTUAL_CHEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SLOT_SLOT_PLAYER_ID);
    }

    @Override
    public UniqueKey<SlotRecord> getPrimaryKey() {
        return Keys.KEY_SLOT_PRIMARY;
    }

    @Override
    public List<ForeignKey<SlotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SLOT_IBFK_1);
    }

    private transient ChestPath _chest;

    /**
     * Get the implicit join path to the <code>mc_virtual_chest.chest</code>
     * table.
     */
    public ChestPath chest() {
        if (_chest == null)
            _chest = new ChestPath(this, Keys.SLOT_IBFK_1, null);

        return _chest;
    }

    @Override
    public Slot as(String alias) {
        return new Slot(DSL.name(alias), this);
    }

    @Override
    public Slot as(Name alias) {
        return new Slot(alias, this);
    }

    @Override
    public Slot as(Table<?> alias) {
        return new Slot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Slot rename(String name) {
        return new Slot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Slot rename(Name name) {
        return new Slot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Slot rename(Table<?> name) {
        return new Slot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Slot where(Condition condition) {
        return new Slot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Slot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Slot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Slot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Slot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Slot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Slot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Slot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Slot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Slot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
