/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.sqlite.tables.records;


import dev.entree.vchest.sqlite.tables.Chest;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChestRecord extends UpdatableRecordImpl<ChestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>chest.chest_num</code>.
     */
    public void setChestNum(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>chest.chest_num</code>.
     */
    public Integer getChestNum() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>chest.chest_player_id</code>.
     */
    public void setChestPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>chest.chest_player_id</code>.
     */
    public Integer getChestPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>chest.chest_expires_at</code>.
     */
    public void setChestExpiresAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>chest.chest_expires_at</code>.
     */
    public LocalDateTime getChestExpiresAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChestRecord
     */
    public ChestRecord() {
        super(Chest.CHEST);
    }

    /**
     * Create a detached, initialised ChestRecord
     */
    public ChestRecord(Integer chestNum, Integer chestPlayerId, LocalDateTime chestExpiresAt) {
        super(Chest.CHEST);

        setChestNum(chestNum);
        setChestPlayerId(chestPlayerId);
        setChestExpiresAt(chestExpiresAt);
        resetChangedOnNotNull();
    }
}
