/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.sqlite.tables.records;


import dev.entree.vchest.sqlite.tables.Slot;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SlotRecord extends UpdatableRecordImpl<SlotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>slot.slot_slot</code>.
     */
    public void setSlotSlot(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>slot.slot_slot</code>.
     */
    public Integer getSlotSlot() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>slot.slot_chest_num</code>.
     */
    public void setSlotChestNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>slot.slot_chest_num</code>.
     */
    public Integer getSlotChestNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>slot.slot_player_id</code>.
     */
    public void setSlotPlayerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>slot.slot_player_id</code>.
     */
    public Integer getSlotPlayerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>slot.slot_item_bytes</code>.
     */
    public void setSlotItemBytes(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>slot.slot_item_bytes</code>.
     */
    public byte[] getSlotItemBytes() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SlotRecord
     */
    public SlotRecord() {
        super(Slot.SLOT);
    }

    /**
     * Create a detached, initialised SlotRecord
     */
    public SlotRecord(Integer slotSlot, Integer slotChestNum, Integer slotPlayerId, byte[] slotItemBytes) {
        super(Slot.SLOT);

        setSlotSlot(slotSlot);
        setSlotChestNum(slotChestNum);
        setSlotPlayerId(slotPlayerId);
        setSlotItemBytes(slotItemBytes);
        resetChangedOnNotNull();
    }
}
