/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.sqlite;


import dev.entree.vchest.sqlite.tables.Chest;
import dev.entree.vchest.sqlite.tables.Player;
import dev.entree.vchest.sqlite.tables.Slot;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>chest</code>.
     */
    public final Chest CHEST = Chest.CHEST;

    /**
     * The table <code>player</code>.
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>slot</code>.
     */
    public final Slot SLOT = Slot.SLOT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chest.CHEST,
            Player.PLAYER,
            Slot.SLOT
        );
    }
}
