/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.sqlite;


import dev.entree.vchest.sqlite.tables.Chest;
import dev.entree.vchest.sqlite.tables.Player;
import dev.entree.vchest.sqlite.tables.Slot;
import dev.entree.vchest.sqlite.tables.records.ChestRecord;
import dev.entree.vchest.sqlite.tables.records.PlayerRecord;
import dev.entree.vchest.sqlite.tables.records.SlotRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChestRecord> CHEST__ = Internal.createUniqueKey(Chest.CHEST, DSL.name(""), new TableField[] { Chest.CHEST.CHEST_PLAYER_ID, Chest.CHEST.CHEST_NUM }, true);
    public static final UniqueKey<PlayerRecord> PLAYER__ = Internal.createUniqueKey(Player.PLAYER, DSL.name(""), new TableField[] { Player.PLAYER.PLAYER_ID, Player.PLAYER.PLAYER_UUID }, true);
    public static final UniqueKey<SlotRecord> SLOT__ = Internal.createUniqueKey(Slot.SLOT, DSL.name(""), new TableField[] { Slot.SLOT.SLOT_SLOT, Slot.SLOT.SLOT_CHEST_NUM, Slot.SLOT.SLOT_PLAYER_ID }, true);
}
