/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.sqlite;


import dev.entree.vchest.sqlite.tables.Chest;
import dev.entree.vchest.sqlite.tables.Player;
import dev.entree.vchest.sqlite.tables.Slot;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>chest</code>.
     */
    public static final Chest CHEST = Chest.CHEST;

    /**
     * The table <code>player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>slot</code>.
     */
    public static final Slot SLOT = Slot.SLOT;
}
