/*
 * This file is generated by jOOQ.
 */
package dev.entree.vchest.mysql.tables.records;


import dev.entree.vchest.mysql.tables.Player;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mc_virtual_chest.player.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mc_virtual_chest.player.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mc_virtual_chest.player.player_uuid</code>.
     */
    public void setPlayerUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mc_virtual_chest.player.player_uuid</code>.
     */
    public String getPlayerUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mc_virtual_chest.player.player_name</code>.
     */
    public void setPlayerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mc_virtual_chest.player.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(Integer playerId, String playerUuid, String playerName) {
        super(Player.PLAYER);

        setPlayerId(playerId);
        setPlayerUuid(playerUuid);
        setPlayerName(playerName);
        resetChangedOnNotNull();
    }
}
